#!/bin/csh
#makeinput
#/dev/shm/uffegj

setenv CWD `pwd`
setenv TMPDIR `mktemp -p /dev/shm/ -u`
mkdir $TMPDIR

#KOPIER MARCS TIL $TMPDIR
# cp ..... $TMPDIR/
# cd $TMPDIR
# ...koer marcs...
# mv mxmodel.dat $CWD/...
# cd $CWD
# rm -rf $TMPDIR 
#
#

cp -r ./* $TMPDIR/.
cd $TMPDIR 

cp $CWD/mxms7marcs1.input mxms7.input
cp $CWD/exo/t145g45j4GGPeK23.arciv  arcivaaa.dat
./GGchem/marcs_test2
mv mxmodel.dat $CWD/exo/t1425g45j4GGPeK23.dat
mv arcivaab.dat $CWD/exo/t1425g45j4GGPeK23.arciv
mv mxms7.output $CWD/mxms7.output
mv fort.66 $CWD/fort.66
mv ppel_before.dat $CWD/.
mv ppel_after.dat $CWD/.

#mv fort.79 op.dat
rm spectrum.dat
rm fort.*
#rm mxms7.input
#rm FLUX.DAT
#rm arcivaaa.dat

rm -rf $TMPDIR
